site_name: ESTACION ASTRONOMICA RIO GRANDE
site_url: https://github.com/casescas/Equipo-4-PP2-ASTRONOMICA-2C-2025
repo_url: https://github.com/casescas/Equipo-4-PP2-ASTRONOMICA-2C-2025
repo_name: Equipo-4-PP2-ASTRONOMICA-2C-2025

theme:
  name: material

nav:
  - Inicio: index.md
  - Guia de Uso: Guia_de_Uso.md
  - API, Workflow y Backfill: API_Flujo_Backfill.md
  
  - Reportes: 
    - Introducci√≥n: Reportes.md
    - Reporte de modelo EfficientNet_B0: Reporte_EfficientNet_B0.md
    - Reporte de modelo EfficientNet_B3: Reporte_EfficientNet_B3.md
  - Plan de Escalamiento: Plan_de_Escalamiento.md

docs_dir: 06.Docs